GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/3

###
POST http://localhost:3000/usuarios/
Content-type: application/json

{
    "nombre": "Ana Karen",
    "apellido": "Cabrera",
    "email": "ak2@gmail.com"

}

###
PUT http://localhost:3000/usuarios/2
Content-type: application/json

{
    "nombre": "Julio",
    "apellido": "Carmona",
    "email": "julioCarmona@gmail.com"

}